### ISSUE TITLE
encrypted login storage

### ISSUE THREAD

**Issue by mastergberry** [UCSB-CS56-Projects/cs56-utilities-password-generator#10]
Make this project a bit more useful, rather than just generating random passwords, allow the user to store logins to services.  Store all of this information in some encrypted file that requires a master password (that the user must create on their own) to unlock the content.  There are several applications like this that already exist that can be used as a good guideline on how to make a similar styled application.

Program must be properly secured with cryptography libraries to earn the full 500 points.

~Estimated 500 points

**Comment by arda-** [comment]
If possible by the owners of the repo, I would suggest renaming this issue to more specifically mention encrypted login storage.
