### ISSUE TITLE
Implement JUnit testing

### ISSUE THREAD

**Issue by arda-** [UCSB-CS56-Projects/cs56-utilities-password-generator#14]
There currently are no Test.java files in /src, so ```ant test``` successfully builds, tests nothing, and returns a positive result. All functions and methods in Password.java need unit tests.

Note: another long-term goal for more complex GUI work would also require unit testing of the GUI, which would most likely be done with the Robot testing framework. But, for the time being, that’s beyond the scope of this project.

Proposed **100 points**
proposed label: Enhancement

**Comment by PazZaitGivon** [comment]
looks good!
