### ISSUE TITLE
Create user prompts upon click of "generate" button

### ISSUE THREAD

**Issue by vincenicoara** [UCSB-CS56-Projects/cs56-utilities-password-generator#15]
We would like to implement code that:

* Checks for valid user input and displays error message if input is invalid. Invalid input denotes: 
   * illogical range values
   * entry of characters that are not special characters in text-box
   * checking the "include your own special characters" box, but not actually including special characters. 

Proposed point value: **100 points**

**Comment by PazZaitGivon** [comment]
also if minimum and maximum are the same make the exact number instead of crashing
