### ISSUE TITLE
Restructuring and renaming of password generating methods.

### ISSUE THREAD

**Issue by vincenicoara** [UCSB-CS56-Projects/cs56-utilities-password-generator#18]
- Re-factor variables and method names to be more descriptive and human readable. 
- Add comments describing code functionality.
- Include javadoc comments. 

Proposed Point Value: **150 points**

**Comment by PazZaitGivon** [comment]
Much much better now

**Comment by tnlarson** [comment]
There still need to be javadoc comments included, but we've redone the password generate algorithm as well. It's currently in Password.java

**Comment by tnlarson** [comment]
I've added javadoc comments for the new generate functions in Password.java.
