### ISSUE TITLE
Ability to Generate Multiple Passwords

### ISSUE THREAD

**Issue by vincenicoara** [UCSB-CS56-Projects/cs56-utilities-password-generator#19]
- Generate multiple passwords at the same time
- Use as modular function that returns arrayList of passwords. 
- Corresponding JUnit testing for the function

Proposed point value: **50 points**

- Add the corresponding multiple password generation feature to the GUI

Proposed point value **50 points**

**Comment by arda-** [comment]
I would add the following as well:
* corresponding unit test for function (for the same 50 points)

And
* add the multiple password generation feature to GUI - another **50 points**

for a total of **100 points**

**Comment by PazZaitGivon** [comment]
approved
