### ISSUE TITLE
Add advanced features to text fields (ghost text, control of internal booleans)

### ISSUE THREAD

**Issue by arda-** [UCSB-CS56-Projects/cs56-utilities-password-generator#24]
Though the current solution of issue #11 fulfills the features we set out to create, the current gui is not yet in the form we would have liked it to be. 

The following improvements still need to be made:
* Implement "ghost text" (similar to how the username/password string disappears on elegant login promts) for each of the min/max fields for each character type.
* implement "ghost text" for the "leave blank for default set of characters" prompt, which would reaplce the "if unchecked..." message
* implement the field for user special characters to have listeners that change the includeUserSpecial boolean of the password object
     * if the field is left empty, assume the user wants the default set of special characters
     * if the field has new text entered in it, set those as the userSpecialChars string to draw the special characters from. (this function already exists, but is triggered by the generate button, and not the presence of text in the field for user special chars).
     * if the field is changed back to empty, assume the user wants the default set, again.\
* if any of the min/max fields are filled in, **automatically check their associated text box**. if any of the min/max fields go back to containing an empty string, automatically uncheck them.
* set the text fields "uppercase", "lowercase" etc to be clickable regions that activate their checkboxes

here's a mockup of this more elegant interface with ghost text:
![Imgur](http://i.imgur.com/YM3Wn1M.jpg)

**Comment by PazZaitGivon** [comment]
Looks good estimated 350 points

**Comment by vincenicoara** [comment]
You can either aim for the same appearance as the above mockup, or you can come up with your own. Keep the same functionality/fields.

**Comment by tnlarson** [comment]
We've cleaned up the GUI; it looks much better now.
