### ISSUE TITLE
Allow specific characters for ALL CharTypes.

### ISSUE THREAD

**Issue by tnlarson** [UCSB-CS56-Projects/cs56-utilities-password-generator#27]
Right now, the password generator lets you specify which special characters you want to be included (omitting those you do not type). But what if the user only wants to include certain uppercase letters, or lowercase letters, or digits? Refactor the functionality of the program (for both the command line and GUI) to allow this functionality for ALL character types. Proposed point value: **200 pts**

**Comment by vincenicoara** [comment]
W16 OK
