### ISSUE TITLE
Fix the inheritance/class hierarchy to follow the MVC design pattern

### ISSUE THREAD

**Issue by giovanni-rojas** [UCSB-CS56-Projects/cs56-utilities-password-generator#29]
The MVC (Model-View-Controller) design pattern is used to aid implementing user interfaces on computers. It divides a given software pattern into three inter-connected parts:

Model: directly manages data, logic, and rules of application (Password.Java)

View: output representation of information (PasswordGUI.java, CommandLine.java)

Controller: accesses input and converts it to commands for the model or view

More information can be found here: http://programmers.stackexchange.com/questions/127624/what-is-mvc-really

The models are there and the views are there, but a controller needs to be added to keep those models and views separate (as opposed to what we have now). 
**Point value: 150 pts**

**Comment by vincenicoara** [comment]
W16 OK
