### ISSUE TITLE
Change the structure of how to set up the different character types (uppercase, lowercase, etc)

### ISSUE THREAD

**Issue by giovanni-rojas** [UCSB-CS56-Projects/cs56-utilities-password-generator#31]
The way the character types are constructed is a bit weird. Also, in order to access a specific CharType, the programmer has to loop through the array of CharTypes to find what they want. Perhaps it is better to represent the array of all CharTypes with a set of key-value pairs? 

**Point value: 100 pts**

**Comment by pconrad** [comment]
Until there is reasonable JUnit test coverage, this issue is NOT approved.    Test coverage MUST be restored before this can proceed.

**Comment by giovanni-rojas** [comment]
Hey Professor Conrad,

This is me and my partner's project from Winter 2016 so I'm a little confused about your email?

All the best,
Giovanni Rojas

Mobile: (415)307-8752
Email: gio.rojas15@gmail.com
