### ISSUE TITLE
Slecting Special characters does not work 

### ISSUE THREAD

**Issue by EdieS** [UCSB-CS56-Projects/cs56-utilities-password-generator#35]
If the user changes the "Include Special Characters:" text field box after running the program, the program does not pick up this change of special characters to be included in the password. The program outputs error message "One or more of special characters are not valid". Also the program does not see the special character in the text field in the generated password.

**point value: 300**

**Comment by jhpenger** [comment]
500pts

**Comment by Christiannewkirk** [comment]
Cannot recreate bug in the original code. Please follow up with a comment that includes a detailed set of steps to recreate bug in original code. Thanks.
