### ISSUE TITLE
Clean up GUI

### ISSUE THREAD

**Issue by mastergberry** [UCSB-CS56-Projects/cs56-utilities-password-generator#9]
~Depends https://github.com/UCSB-CS56-Projects/cs56-utilities-password-generator/issues/4

The GUI isn't very nice right now. Organize it to be more user friendly.

~ Estimated 100 points

**Comment by arda-** [comment]
Planned improvements to the current GUI:
* Reformat layout of text and text boxes (2-column format of "prompt: [entry in text box]" is more appropriate)
* Add minimum/maximum window size (So no clipping of content occurs if window is resized)

**Comment by PazZaitGivon** [comment]
Gui looks a lot nicer now!
